best_threshold: 0.4134661502512615
gender_dict:
  0: Male
  1: Female
location_dict:
  0: Sydney
  1: Melbourne
  2: Brisbane
  3: Perth
  4: Adelaide
  5: Hobart
  6: Darwin
  7: Canberra
occupation_dict:
  0: Engineer
  1: Artist
  2: Doctor
  3: Teacher
  4: Sales
  5: Lawyer
  6: Scientist
  7: Accountant
  8: Nurse
  9: Software Developer
product_type_dict:
  0: Laptop
  1: Smartphone
  2: Camera
  3: Cosmetics
  4: Handbag
  5: Shoes
  6: TV
  7: Perfume
  8: Watch
  9: Clothes
